# 需将ffmpeg的bin目录设为环境变量
server:
  port: 80
app:
  # 存储转码视频的文件夹地址
  video-folder: "D:\\Program Files (x86)\\ffmpeg\\video"

spring:
  servlet:
    multipart:
      enabled: true
      # 不限制文件大小
      max-file-size: -1
      # 不限制请求体大小
      max-request-size: -1
      # 临时IO目录
      location: "${java.io.tmpdir}"
      # 不延迟解析
      resolve-lazily: false
      # 超过1Mb，就IO到临时目录
      file-size-threshold: 1MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 连接池名称
      pool-name: DateHcx
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 180000000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间 30分钟
      max-lifetime: 18000000
      # 连接超时时间 30秒
      connection-timeout: 30000
      # 测试连接
      connection-test-query: SELECT 1
  web:
    resources:
      static-locations:
        - "classpath:/static/"
        - "file:${app.video-folder}" # 把视频文件夹目录，添加到静态资源目录列表
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000
    database: 0
    jedis:
      pool:
        max-idle: 30
  rabbitmq:
    host: 127.0.0.1
    username: hcx
    password: 123456
    port: 5672
    listener:
      simple:
        #最小消费者
        concurrency: 10
        max-concurrency: 10
mybatis-plus:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.hcx.seckill.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.hcx.seckill.*.mapper: debug

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: false
